### ISSUE TITLE
Feedback from a `bbdiff` user

### ISSUE THREAD

**Issue by Fil** [bomsy/brackets-compare#10]
BBEdit "diff" mode is very efficient, here are the tremendously useful features that I miss when I use brackets-compare:

1. `bbdiff`, a CLI which takes two filenames as arguments and opens the editor in doff mode between the two files
2. compare mode opens 3 windows:
```
TEXT1 | TEXT2
    diff
```
in the diff window, you get a list of chunks with line numbers, and you can go quickly through the list with the keyboard or mouse, updating the TEXT1 and TEXT2 windows ; then with a click you can _apply changes_ from TEXT1 to TEXT2 or the other way.
3. you can select two filenames in the list/project pane and select a contextual "compare selected documents" menu
4. (There's a directory diff mode also, but I personally prefer to directly use `diff -r`)

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.

**Comment by Fil** [comment]
I don't know why I was not able to install it this time. Install from URL > `https://github.com/bomsy/brackets-compare` gives me an (unspecified) error ("Erreur d'extension" in French)

**Comment by bomsy** [comment]
Have you tried installing from the extension registry?

**Comment by bomsy** [comment]
Try installing again! thanks

**Comment by Fil** [comment]
Installing from the registry works (it loads 0.2.4 from amazon). But installing from `https://github.com/bomsy/brackets-compare/` stil doesn't work.

**Comment by bomsy** [comment]
yeah only the install from registry works
