### ISSUE TITLE
Better workflow

### ISSUE THREAD

**Issue by Wikunia** [bomsy/brackets-compare#12]
Hi @bomsy!

Thanks for this extension :) I have some improvement ideas:

1. At the moment the first file must be in the current project file so it isn't possible to add a file with drag & drop to the working files and compare them because the context option 'Compare with file..' isn't available.
2. When the user choose the compare with file option a open file dialog appears and I need to choose the same directory to open the second file :/ An idea would be to check whether the user is a split mode and then the user can choose to compare these two files via the View menu.

What do you think about it?

**Comment by bomsy** [comment]
Hey @Wikunia
Thanks for your ideas! Great suggestions!
1. I'll look into fixing this.
2. I can add an option to the view menu to compare the two files, when split mode is on. 
Will that work?

**Comment by Wikunia** [comment]
You're welcome! 
I think that it should work with split view. I made some extensions but nothing with split view but you can send me a mail if you need some help :)

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.
