### ISSUE TITLE
Brackets behavior after closing compare

### ISSUE THREAD

**Issue by dvorapa** [bomsy/brackets-compare#13]
Hello, after I close compare interface (with blue x on the right), I am not able to change project (project folder) I'm currently working in and the file menu looks broken.

**Comment by bomsy** [comment]
Ok. thanks.. i'll look into this

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.

**Comment by dvorapa** [comment]
I don't use Brackets anymore, because its developers don't want to support Linux. Two latest releases couldn't be installed at all.

**Comment by bomsy** [comment]
ok cool. Fixed the issue though.
