### ISSUE TITLE
Method and view ideas

### ISSUE THREAD

**Issue by dvorapa** [bomsy/brackets-compare#14]
Hello, this extension is exactly, what I need, but I have two ideas, how to make your extension better:

- In all modern browsers, where compare interface is natively present, it works this way:
  1. open 1st file
  2. open 2nd file and let it active/openned
  3. right click to 1st file and select "compare"
  4. the editor compares currently openned file with the one you clicked on

It would be great to change the behavior of your extension to behave this way. I think it is all ways better than select file dialog. Brackets API contains variable for currently openned file, so no problem there.

- Accorfing to me it should let the files/project menu openned and automatically close compared view after selecting another file to view. Just saying

**Comment by bomsy** [comment]
I've revamped the plugin. it's still in development, but its all on github. It has not been released yet. The workflow has changed. Check it out.

**Comment by dvorapa** [comment]
I'll check, but I moved out from Brackets (because of poor support for Linux, currently I even can not install three of latest versions on newest fully updated 3rd most used Linux distribution in the world and there also is not any support for native OS menus, I can not open any file by clicking on it in native OS file manager - opens plain Brackets and not file - and a stability of Brackets is really bad these days. Some bugs are also there for more than three versions - e.g. the annoying notification after first install, which can not be closed by clicking the x button, the only way is to restart Brackets)
