### ISSUE TITLE
Doesn't seem to mark differences

### ISSUE THREAD

**Issue by hobyvh** [bomsy/brackets-compare#15]
I'm using Brackets r 1.2 build 1.2.0-15697 and the compare plugin doesn't seem to be working. I can load two files but no differences are marked or anything. It's just like I'm opening them in split view.

Is there a compatibility problem or something else going on?

**Comment by bomsy** [comment]
i'll look into it. cheers

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.
