### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by topwebs** [bomsy/brackets-compare#18]
This extension doesn't work at all with the latest Brackets. The context menu does not even show the option to compare.

**Comment by t0mtaylor** [comment]
:+1:

**Comment by petrchutny** [comment]
Same here

**Comment by sbgraphic** [comment]
same here

**Comment by soybean26** [comment]
Same

**Comment by bomsy** [comment]
This needs a complete rewrite...does not support the current brackets

**Comment by mediaformat** [comment]
+1 for a rewrite

**Comment by bomsy** [comment]
A rewrite is coming up.

**Comment by petrchutny** [comment]
Great, thanks :) looking forward!

**Comment by carinlynchin** [comment]
;(   same here

**Comment by bomsy** [comment]
I've revamped the plugin. it's still in development, but its all on github. It has not been released yet.

**Comment by carinlynchin** [comment]
cool :) So do I just download it and install with the zip upload? 

    On Tuesday, March 22, 2016 11:02 AM, Hubert Boma Manilla <notifications@github.com> wrote:
 

 I've revamped the plugin. it's still in development, but its all on github. It has not been released yet.—

**Comment by bomsy** [comment]
no ...i've not released a zip file yet. The changes are just on github.

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.

**Comment by topwebs** [comment]
When I try to install, it says "Installation failed."

**Comment by bomsy** [comment]
cool thanks ... looking into it!

**Comment by carinlynchin** [comment]
yea same here. Here is a screenshot


 

    On Monday, April 25, 2016 12:53 PM, Hubert Boma Manilla <notifications@github.com> wrote:
 

 cool thanks ... looking into it!—

**Comment by SkellyCT** [comment]
I can't get it to work either. "Extension error" after uploading.

**Comment by bomsy** [comment]
Hi, ive fixed it. you can download v0.2.4

**Comment by topwebs** [comment]
Well, it installs now, but clicking the button doesn't show any differences at all. Also, the scrolling of the two panes should be synchronized.

**Comment by bomsy** [comment]
do you have a screen shot of what you see?

**Comment by topwebs** [comment]
There's nothing unusual to see. File on right and left with a difference in a line, extension button highlighted, but the file difference not highlighted.

**Comment by bomsy** [comment]
can you let me know what version of brackets you are using?

**Comment by topwebs** [comment]
Latest 1.6. Tried with files with one different word in each. Clicking the diff button does nothing.

**Comment by bomsy** [comment]
And you don't have any error message showing up top

**Comment by bomsy** [comment]
Can you write the steps, so i can try to reproduce the error?

**Comment by topwebs** [comment]
Just followed the directions on https://github.com/bomsy/brackets-compare. Clicking the Show Diff button does nothing. No error messages. 

These are the extensions I have installed:

Brackets Git
brackets-compare
BracketstoIX
eqFTP
Extensions Rating
Extract for Brackets (Preview)
SVG Preview

**Comment by topwebs** [comment]
After trial and error, when the extension BracketstoIX is enabled, your extension does not work. When that extension is disabled, the compare extension works.

**Comment by topwebs** [comment]
When you revert chunk and copy the diff from one file to the other, there seems to be no way to save the edited file.

**Comment by bomsy** [comment]
At the moment changes to the files cannot be saved. You can only view diffs. That's a feature being worked on.
