### ISSUE TITLE
question regarding issue with newer brackets

### ISSUE THREAD

**Issue by carinlynchin** [bomsy/brackets-compare#20]
I would like to contribute...can you give me a summary of why it doesn't work with new brackets and maybe I can help some?

**Comment by bomsy** [comment]
Hey, a couple of things. One of those is
- brackets-compare was written before the the existence of split views, so i had to implement those.
There are a couple of other things..
i'm in the process of overhauling it. I should push something in the next week or so.
 Some help would be great! Will keep you updated.

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.
