### ISSUE TITLE
newer one won't install right

### ISSUE THREAD

**Issue by carinlynchin** [bomsy/brackets-compare#22]
When i drag the zip file into brakcets or enter the url..it doesn't install right and i get an error
<img width="887" alt="screen shot 2016-04-12 at 11 22 21 am" src="https://cloud.githubusercontent.com/assets/1210918/14465457/14e08e8e-00a1-11e6-8873-84f211f62061.png">

**Comment by bomsy** [comment]
I've not released the new one yet. Would do that soonest.

**Comment by carinlynchin** [comment]
oh i thought you said it was in the zip file...my bad
 

    On Tuesday, April 12, 2016 2:46 PM, Hubert Boma Manilla <notifications@github.com> wrote:
 

 I've not released the new one yet. Would do that soonest.—

**Comment by bomsy** [comment]
hey i've released v0.2.0. Please try it out and let me know.
