### ISSUE TITLE
Not able to install this extention in brackets.Getting error

### ISSUE THREAD

**Issue by prasadpatil14** [bomsy/brackets-compare#26]
I installed latest version of brackets but while installing this extention I am getting following error.
![erre](https://cloud.githubusercontent.com/assets/13998264/15238821/48f464f4-18fa-11e6-9afe-186b32d8a14d.jpg)

**Comment by jhejlik** [comment]
I get the the same error.
Brackets 1.6.0-16680 (release 3df0ac6fa)

**Comment by bomsy** [comment]
released v 0.2.5. pls check!

**Comment by bomsy** [comment]
v 0.2.6 is latest

**Comment by bomsy** [comment]
at 0.2.7
