### ISSUE TITLE
It does not save or update the changes I made

### ISSUE THREAD

**Issue by AngelLestat** [bomsy/brackets-compare#31]
After editing all differences  in the compare mode, it does not save those differences, both files remains the same, I already tried in different positions or changing the folder in which I am working on it.

Is that a bug?  Or this extensions just show differences and does nothing to correct them?
In the last case, why you can press in the arrows to fix the differences that you want if later does not save the changes?

**Comment by bomsy** [comment]
@AngelLestat hey, it does not save yet. Planning to do some work on that
https://github.com/bomsy/brackets-compare/issues/24
