### ISSUE TITLE
Cannot save changes made in diff view

### ISSUE THREAD

**Issue by Olatunji-Longe** [bomsy/brackets-compare#35]
Cannot save changes made in diff view. This issue has been closed in 2015, but still exixts even in 2017. Why was it closed?

**Comment by M4TH76** [comment]
Add on line 158 of main.js:

MainViewManager.setActivePaneId(panes[0])
var document = DocumentManager.getCurrentDocument()
document.setText(compareView.editor().getValue())

it will copy the modified content to the left pane document

**Comment by mnishig** [comment]
In my installation is not line 158,  M4TH76's patch put to line 156 after else { ,
and run perfectly with following patch.

```
--- main.js	2017-05-04 00:18:12.000000000 +0900
+++ main.js.fix	2017-05-04 00:18:34.000000000 +0900
@@ -153,11 +153,15 @@
           compareEditor.css("height", editorCurrentHeight + "px");
           hdiff = compareEditor.parent().height() - editorCurrentHeight;
         } else {
+          MainViewManager.setActivePaneId(panes[0]);
+          var document = DocumentManager.getCurrentDocument();
+          document.setText(compareView.editor().getValue()); 
+          
           comparePanel.hide();
           target.innerHTML = "";
           compareView = null;
-          editor.removeClass("hide");
-          WorkspaceManager.off(WorkspaceManager.EVENT_WORKSPACE_UPDATE_LAYOUT, onWorkspaceLayoutUpdate);
+          editor.removeClass("hide");    
+        WorkspaceManager.off(WorkspaceManager.EVENT_WORKSPACE_UPDATE_LAYOUT, onWorkspaceLayoutUpdate);
           Sidebar.show();
         }
       });

```

**Comment by jthomae1** [comment]
I can confirm the same behaviour, changes I made in the diff view are not saved when I leave the view.

**Comment by nlourenco** [comment]
Commit not reflected in recent download from Brackets Extension manager. Can confirm @mnishig solution, but must save and close & re-open Brackets.
